In [1]:
import pandas as pd

# Series

In [2]:
ser_obj = pd.Series(range(10, 20))
print(ser_obj)
# Series类似一维数组, 带有索引(自动生成)
print('-'*50)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------------------------------------

In [4]:
print(ser_obj.values)
print(type(ser_obj.values)) 
# Series的values实际上是ndarray
print(ser_obj.index)
print(type(ser_obj.index))
# 索引的类型就是RangeIndex
ser_obj.dtype 
# 数据的类型

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)
<class 'pandas.RangeIndex'>

dtype('int64')

In [5]:
print(ser_obj[9])
print(ser_obj[0:5])
print(ser_obj[10]) 
# 不存在的索引会报KeyError

19
0    10
1    11
2    12
3    13
4    14
dtype: int64

KeyError: 10

In [6]:
print(ser_obj * 2)  
# 对每个元素运算
print(ser_obj > 15) 
# 返回一个bool序列, 判断每个元素是否大于15

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

In [9]:
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
# 可以将字典直接转换为Series
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print(ser_obj2.index)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
Index([2001, 2005, 2003], dtype='int64')
17.8

array([17.8, 20.1, 16.5])

In [18]:
ser_obj2 = pd.Series(year_data)
print(ser_obj2.name) 
print(ser_obj2.index.name)  
print('-'*50)
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
# 给Series和索引加上名字
print(ser_obj2.head())  #head默认显示前5行
type(ser_obj2)

None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64

pandas.Series

# DataFrame

In [20]:
import numpy as np
t = pd.DataFrame(np.arange(12).reshape((3,4)))
# 将ndarray转化为DataFrame
# DataFrame类似二维数组, 带有行索引和列索引
print(t)
print('-'*50)
array = np.random.randn(5,4)
# 创建一个5行4列的随机数组, 元素服从正态分布
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head())
type(df_obj)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------
[[ 0.31067319  0.19753172  0.03765134 -0.32861912]
 [ 1.39988231  0.10436267  1.64926386 -0.83981578]
 [-1.14236865  0.58363786 -1.61159328 -0.78060079]
 [ 0.64903323 -0.22069186 -0.85800952  0.2024408 ]
 [-2.07132616 -0.13199054  0.04928339 -0.32405838]]
--------------------------------------------------
          0         1         2         3
0  0.310673  0.197532  0.037651 -0.328619
1  1.399882  0.104363  1.649264 -0.839816
2 -1.142369  0.583638 -1.611593 -0.780601
3  0.649033 -0.220692 -0.858010  0.202441
4 -2.071326 -0.131991  0.049283 -0.324058

pandas.DataFrame

In [22]:
t.loc[0] 
# 单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [23]:
d =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
# 将字典列表变成DataFrame
df=pd.DataFrame(d)
# 最外层变成行, 关键字变成列, 没有数据会变成NaN
print(df)
print(type(df.values))

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>

In [24]:
pd.Series(1, index=list(range(3,7)), dtype='float32')
# 创建一个Series, 索引从3到6, 值全为1, 数据类型为float32(自动广播)

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [27]:
dict_data = {'A': 1,
             'B': pd.Timestamp('20251221'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             # 按索引对齐
             'D': np.array([1,2,3,4],dtype='int32'),
             # 按位置填充
             # 两种都被转换成Series
             'E': ["Python","Java","C++","C"],
             'F': 'Programming' }
# 将字典转换成DataFrame
df_obj = pd.DataFrame(dict_data)
print(df_obj)
print('-'*50)
print(df_obj.index) 
# 不可以单独修改某个索引值
print(df_obj.columns)
df_obj.dtypes 
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型

   A          B    C  D       E            F
0  1 2025-12-21  1.0  1  Python  Programming
1  1 2025-12-21  1.0  2    Java  Programming
2  1 2025-12-21  1.0  3     C++  Programming
3  1 2025-12-21  1.0  4       C  Programming
--------------------------------------------------
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

A             int64
B    datetime64[us]
C           float32
D             int32
E               str
F               str
dtype: object

实际上, DataFrame的每一列都是一个Series

In [29]:
dates = pd.date_range('20260101', periods=6) 
#默认freq='D'，每行一天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
# 日期设置为"索引", 列名设置为"A, B, C, D"
print(df)
print('-'*50)
print(df.index)

                   A         B         C         D
2026-01-01 -1.000745  0.449141 -0.184593 -0.613499
2026-01-02 -0.030276  0.239184 -0.413855  1.900859
2026-01-03 -1.170540 -0.509876 -1.980355 -1.002505
2026-01-04  0.770661  0.091531 -1.884370  1.671773
2026-01-05 -1.596723  0.043837 -0.163426  0.116644
2026-01-06  1.637418 -1.324649  0.456373  0.532612
--------------------------------------------------
DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[us]', freq='D')

In [33]:
print(df_obj)
print(type(df_obj))
print(df_obj['B'])
#取B列出来, 类型是Series
print(type(df_obj['B']))
print(df_obj.loc[1])
#取第1列出来, 类型是Series
print(type(df_obj.loc[1]))

   A          B    C  D       E            F
0  1 2025-12-21  1.0  1  Python  Programming
1  1 2025-12-21  1.0  2    Java  Programming
2  1 2025-12-21  1.0  3     C++  Programming
3  1 2025-12-21  1.0  4       C  Programming
<class 'pandas.DataFrame'>
0   2025-12-21
1   2025-12-21
2   2025-12-21
3   2025-12-21
Name: B, dtype: datetime64[us]
<class 'pandas.Series'>
A                      1
B    2025-12-21 00:00:00
C                    1.0
D                      2
E                   Java
F            Programming
Name: 1, dtype: object
<class 'pandas.Series'>

In [34]:
df_obj['G'] = df_obj['D'] + 4
# 增加列
print(df_obj.head(n=3))
del(df_obj['G'])
# 删除列
print(df_obj.head())

   A          B    C  D       E            F  G
0  1 2025-12-21  1.0  1  Python  Programming  5
1  1 2025-12-21  1.0  2    Java  Programming  6
2  1 2025-12-21  1.0  3     C++  Programming  7
   A          B    C  D       E            F
0  1 2025-12-21  1.0  1  Python  Programming
1  1 2025-12-21  1.0  2    Java  Programming
2  1 2025-12-21  1.0  3     C++  Programming
3  1 2025-12-21  1.0  4       C  Programming

# Series索引

In [36]:
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
ser_obj.index

a    0
b    1
c    2
d    3
e    4
dtype: int64

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [37]:
# 用行索引来取值
print(ser_obj['b']) # 取索引为b的元素
print(ser_obj.iloc[2]) # 取2号元素

1
2

In [38]:
# 索引切片
print(ser_obj[1:3])  # 用位置取数据, 不包含3
print(ser_obj['b':'d'])  #用标签取数据, 包含d

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64

In [39]:
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj[['a', 'e']])
# 按位置和标签取不连续索引
# iloc只能传一个参数, 为了取不连续索引, 就将[0, 2, 4]作为列表传入iloc, 所以有两层括号

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64

In [41]:
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)
print('-'*50)
print(ser_obj[ser_bool])
print(ser_obj[ser_obj > 2])
# 使用布尔索引, 只输出bool为True的行

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool
--------------------------------------------------
d    3
e    4
dtype: int64
d    3
e    4
dtype: int64

# DataFrame索引

In [45]:
df_obj = pd.DataFrame(np.random.randn(5,4), columns = list('abcd'))
print(df_obj.head())

          a         b         c         d
0 -2.397952 -0.790284  0.844446 -0.753673
1 -0.885137 -0.364465 -0.715936  0.272375
2  0.004817 -0.409157  1.185988 -0.900076
3 -0.118487 -0.052133 -1.573163  0.205230
4  0.202513  0.635519 -1.022307  0.837275

In [48]:
print(df_obj['a']) 
# 返回Series类型
print(type(df_obj['a']))
print('-'*50)
print(df_obj[['a']]) 
print(type(df_obj[['a']]))
# 返回DataFrame类型
# 因为传入的本质上是一个标签列表

0   -2.397952
1   -0.885137
2    0.004817
3   -0.118487
4    0.202513
Name: a, dtype: float64
<class 'pandas.Series'>
--------------------------------------------------
          a
0 -2.397952
1 -0.885137
2  0.004817
3 -0.118487
4  0.202513
<class 'pandas.DataFrame'>

loc标签索引

In [49]:
# Series
print(ser_obj)
print(ser_obj['b':'d']) # 不建议使用
print(ser_obj.loc['b':'d']) # 建议使用loc, 前闭后闭
print('-'*50)

a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
d    3
dtype: int64
b    1
c    2
d    3
dtype: int64
--------------------------------------------------

In [50]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5,4),columns = list('abcd'), 
                      index=list('abcde'))
print(df_obj)
print('-'*50)
print(df_obj['a'])  
# 不建议使用这种方式, 取的是列(默认按columns)
print('-'*50)
print(df_obj.loc['a'])  
# 取的是行
print('-'*50)

          a         b         c         d
a  0.237989  1.836875  0.792550 -0.829914
b -1.068878 -0.715301 -0.955519 -1.409500
c -0.605513  0.055001 -0.462563  0.344262
d  0.205686  0.871894 -1.036604  0.741979
e  1.301248 -0.617675  1.822550  1.235696
--------------------------------------------------
a    0.237989
b   -1.068878
c   -0.605513
d    0.205686
e    1.301248
Name: a, dtype: float64
--------------------------------------------------
a    0.237989
b    1.836875
c    0.792550
d   -0.829914
Name: a, dtype: float64
--------------------------------------------------

In [51]:
print(df_obj.loc['a':'c', 'b':'d']) 
# 连续索引
print(df_obj.loc[['a','c'], ['b','d']]) 
# 不连续索引
print(df_obj.loc[['c'],['b']]) 
# 取一个值, 返回的是一个DataFrame
print(df_obj.loc['c','b']) 
# 取一个值, 返回的是一个元素
# 使用loc或者iloc效率高于直接使用索引

          b         c         d
a  1.836875  0.792550 -0.829914
b -0.715301 -0.955519 -1.409500
c  0.055001 -0.462563  0.344262
          b         d
a  1.836875 -0.829914
c  0.055001  0.344262
          b
c  0.055001
0.05500119070268941

# iloc位置索引(左闭右开)

In [52]:
# Series
print(ser_obj)
print(ser_obj[1:3])
print(ser_obj.iloc[1:3])
print('-'*50)

a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
dtype: int64
b    1
c    2
dtype: int64
--------------------------------------------------

In [58]:
# DataFrame
df_obj=pd.DataFrame(np.random.randn(5,4))
print(df_obj)
print()
print(df_obj.iloc[0:2, 0]) 
print(df_obj.loc[0:2, 0])
# 左闭右开和左闭右闭
print(df_obj.iloc[[0,2], [0,2]]) 
# 不连续索引, 取(0,0)和(2,2)
# 返回的是一个DataFrame
print(df_obj.iloc[0,0]) 
# 取一个值, 返回的是一个元素

          0         1         2         3
0  1.001042 -0.728321 -0.530123 -1.245816
1  0.269101 -1.840455  3.412091  1.231333
2 -2.157688 -0.194062 -3.264633 -0.692470
3 -0.711003 -0.676161 -1.099698  0.118014
4  0.005803 -0.225455  0.689618  0.958180

0    1.001042
1    0.269101
Name: 0, dtype: float64
0    1.001042
1    0.269101
2   -2.157688
Name: 0, dtype: float64
          0         2
0  1.001042 -0.530123
2 -2.157688 -3.264633
1.0010423365276049

# 函数应用

In [59]:
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) 
# 按元素取绝对值

          0         1         2         3
0 -1.639646 -2.015069 -0.374767 -2.166692
1 -0.458696 -1.515331 -1.792618 -0.130554
2 -2.027891 -2.837950 -1.431016 -0.534595
3 -1.447554  0.178370 -2.028237 -1.229024
4 -0.016808 -1.704500 -1.138618 -1.642448
          0         1         2         3
0  1.639646  2.015069  0.374767  2.166692
1  0.458696  1.515331  1.792618  0.130554
2  2.027891  2.837950  1.431016  0.534595
3  1.447554  0.178370  2.028237  1.229024
4  0.016808  1.704500  1.138618  1.642448

用apply(作用在行或列上)和map(作用在每一个元素上)使用lambda表达式

In [60]:
print(df.apply(lambda x : x.max(),axis=0))
# apply里的函数默认作用在每一列上, 取每一列最大值

0   -0.016808
1    0.178370
2   -0.374767
3   -0.130554
dtype: float64

In [61]:
print(df.apply(lambda x : x.max(), axis=1))
# 取每一行最大值

0   -0.374767
1   -0.130554
2   -0.534595
3    0.178370
4   -0.016808
dtype: float64

In [66]:
print(df.map(lambda x : '%.2f' % x))
# 对每个元素应用lambda函数

       0      1      2      3
0  -1.64  -2.02  -0.37  -2.17
1  -0.46  -1.52  -1.79  -0.13
2  -2.03  -2.84  -1.43  -0.53
3  -1.45   0.18  -2.03  -1.23
4  -0.02  -1.70  -1.14  -1.64

# 处理缺失数据

In [67]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0  0.002833 -0.420945  1.656339
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [69]:
print(df_data.isnull())
# 返回一个内容为bool型的DataFrame
print(df_data.isnull().sum()/df_data.shape[0])
# 每一列的缺失率
# 每一列的bool类型求和, 除以行数

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False
0    0.25
1    0.00
2    0.50
dtype: float64

删除缺失数据

In [71]:
print(df_data.dropna(subset=[0], inplace=False))
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
#inplace=False，不改变原DataFrame

          0         1         2
0  0.002833 -0.420945  1.656339
1  1.000000  2.000000       NaN
3  1.000000  2.000000  3.000000

In [ ]:
print(df_data.dropna(axis=1))
# 按照轴1来删除, 即如果某一列有NaN, 就删除该列

填充缺失数据

In [73]:
print(df_data.iloc[:,0].fillna(-100.))
# 将0列的缺失值填充为-100.0, 返回的是一列
print(df_data.fillna(-100.))
# 将每个缺失值都填充为-100.0

0      0.002833
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64
            0         1           2
0    0.002833 -0.420945    1.656339
1    1.000000  2.000000 -100.000000
2 -100.000000  4.000000 -100.000000
3    1.000000  2.000000    3.000000

# 统计与计算

In [75]:
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'], [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])
# 设置层级索引, 即多层次的索引
ser_obj = pd.Series(np.random.randn(12),index=index1)
print(ser_obj)
# 有两层索引的Series

cloth  size
a      0       0.434677
       1      -0.413639
       2       0.397312
b      0       0.851939
       1       0.501507
       2      -0.202518
c      0       0.511457
       1      -0.658684
       2      -0.660053
d      0      -1.782792
       1       0.415440
       2       0.289410
dtype: float64

In [80]:
df_obj=ser_obj.unstack(1)
# 将外层索引转换为列索引, 内层索引转换为行索引
print(df_obj)
# 将两层索引的Series转换成DataFrame

size          0         1         2
cloth
a      0.434677 -0.413639  0.397312
b      0.851939  0.501507 -0.202518
c      0.511457 -0.658684 -0.660053
d     -1.782792  0.415440  0.289410

In [78]:
df_obj.loc[0,'b']=np.nan 
# 将0行的b列的值设为NaN
print(df_obj)
print('-'*50)
print(df_obj.min(axis=0, skipna=True))
# 按行求最小值, 跳过NaN(默认)

cloth         a         b         c         d
size
0      0.434677       NaN  0.511457 -1.782792
1     -0.413639  0.501507 -0.658684  0.415440
2      0.397312 -0.202518 -0.660053  0.289410
--------------------------------------------------
cloth
a   -0.413639
b   -0.202518
c   -0.660053
d   -1.782792
dtype: float64

In [79]:
print(df_obj.describe())
# 描述性统计

cloth         a         b         c         d
count  3.000000  2.000000  3.000000  3.000000
mean   0.139450  0.149494 -0.269093 -0.359314
std    0.479353  0.497821  0.675977  1.234378
min   -0.413639 -0.202518 -0.660053 -1.782792
25%   -0.008164 -0.026512 -0.659369 -0.746691
50%    0.397312  0.149494 -0.658684  0.289410
75%    0.415994  0.325501 -0.073613  0.352425
max    0.434677  0.501507  0.511457  0.415440

# 分组运算

In [81]:
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1, 10, 8),
            'data2': np.random.randint(1, 10, 8)}
df_obj = pd.DataFrame(dict_obj)
print(df_obj)

  key1   key2  data1  data2
0    a    one      9      4
1    b    one      4      2
2    a    two      4      4
3    b  three      2      7
4    a    two      4      3
5    b    two      9      4
6    a    one      1      5
7    a  three      2      8

In [84]:
# 按key1分组后，计算data1，data2的统计信息并附加到原始表格中，并添加表头前缀
k1_sum = df_obj.groupby('key1').mean(numeric_only=True).add_prefix('mean_')
# numeric_only=True, 只对只包含数值的列进行运算
# 添加前缀mean_
print(k1_sum)

      mean_data1  mean_data2
key1
a            4.0    4.800000
b            5.0    4.333333

In [92]:
k1_sum_tf= df_obj.groupby('key1').transform('mean', numeric_only=True).add_prefix('mean_')
# transform指对每个列进行变换,最终形状与原DataFrame相同
# 作用是将每组对应的行的值替换为该组平均值
print(k1_sum_tf)

   mean_data1  mean_data2
0         4.0    4.800000
1         5.0    4.333333
2         4.0    4.800000
3         5.0    4.333333
4         4.0    4.800000
5         5.0    4.333333
6         4.0    4.800000
7         4.0    4.800000

In [93]:
def diff_mean(s):
    """
    返回数据与均值的差值
    """
    return s - s.mean()

print(df_obj.loc[:, ['key1','data1', 'data2']].groupby('key1').transform(diff_mean))
# 选定每一行里的key1列和data1, data2列, 对key1列进行分组, 对每一组每个元素取diff_mean

   data1     data2
0    5.0 -0.800000
1   -1.0 -2.333333
2    0.0 -0.800000
3   -3.0  2.666667
4    0.0 -1.800000
5    4.0 -0.333333
6   -3.0  0.200000
7   -2.0  3.200000

# 处理重复值

In [94]:
df_obj = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})
print(df_obj)

  data1  data2
0     a      0
1     a      2
2     a      1
3     a      3
4     b      0
5     b      0
6     b      3
7     b      0

In [96]:
print(df_obj.duplicated())
# 返回一个布尔Series, 长度与DataFrame相同
# 若一行的值是True, 说明和之前的某行重复了

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
dtype: bool

In [97]:
df_obj[~df_obj.duplicated()]
# 取出不重复的行(使用布尔索引)

  data1  data2
0     a      0
1     a      2
2     a      1
3     a      3
4     b      0
6     b      3

In [98]:
print(df_obj.duplicated('data2'))
# 按照某一列检查重复值

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
dtype: bool

NaN和NaN是否重复?

In [100]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1234')})
df_obj1

   data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     4

In [102]:
df_obj1.duplicated('data1')
# duplicated()方法认为NaN是重复的

0    False
1     True
2     True
3     True
dtype: bool

In [ ]:
print(df_obj1.drop_duplicates('data1'))
# 按data1去除重复行

In [104]:
print(df_obj.drop_duplicates())
# 去除完全相同的行
# 默认inplace=False, 不改变原DataFrame

  data1  data2
0     a      0
1     a      2
2     a      1
3     a      3
4     b      0
6     b      3